language: python
python: 2.7
# https://bitbucket.org/ianb/pastescript/issue/4/
install:
  - pip install paste
  - pip install pastedeploy
  - pip install pastescript
  - pip install -r dev-reqs.txt --use-mirrors
script: nosetests
