language: python
python: 2.7
# https://bitbucket.org/ianb/pastescript/issue/4/
install:
  - sudo apt-get install swig
  - pip install paste pastedeploy pastescript
  - pip install -r dev-reqs.txt --use-mirrors
script:
  - PUSH_TEST_CONFIG=./etc/push-test.ini nosetests
